/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BackgroundPanel: typeof import('./components/BackgroundPanel.vue')['default']
    BottomToolbar: typeof import('./components/BottomToolbar.vue')['default']
    CanvasStage: typeof import('./components/CanvasStage.vue')['default']
    ComponentPanel: typeof import('./components/ComponentPanel.vue')['default']
    HotTitleModal: typeof import('./components/HotTitleModal.vue')['default']
    MainArea: typeof import('./components/MainArea.vue')['default']
    ResourceManager: typeof import('./components/ResourceManager.vue')['default']
    SidebarLeft: typeof import('./components/SidebarLeft.vue')['default']
    SidebarRight: typeof import('./components/SidebarRight.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
